plugins {
    id "com.android.application"
}

def signingPropertiesFile = rootProject.file("keystore.properties")
def signingProperties = new Properties()
if (signingPropertiesFile.exists()) {
    signingProperties.load(new FileInputStream(signingPropertiesFile))
}

android {
    namespace "app.domainwatch.agent"
    compileSdk 34

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId "app.domainwatch.agent"
        minSdk 26
        targetSdk 34
        versionCode 6
        versionName "1.0.5"
    }

    if (signingPropertiesFile.exists()) {
        signingConfigs {
            release {
                storeFile rootProject.file(signingProperties["storeFile"])
                storePassword signingProperties["storePassword"]
                keyAlias signingProperties["keyAlias"]
                keyPassword signingProperties["keyPassword"]
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            if (signingPropertiesFile.exists()) signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
