import type { Prisma } from "@prisma/client";

// Call inside the same transaction AFTER locking/updating the agent row.
// Snapshots survive deletion; timestamps are generated by the server, never the phone.
export async function recordPresence(tx: Prisma.TransactionClient, agentId: string, kind: string) {
  const a = await tx.mobileAgent.findUniqueOrThrow({ where: { id: agentId } });
  await tx.agentPresence.create({ data: { agentId, agentName: a.name, ownerId: a.siteOwnerId, kind, createdAt: new Date() } });
}
